{{- if and .Values.selenoid.enabled .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-selenoid" (include "firecrawl.fullname" .)) .Values.serviceAccount.name }}
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
    app.kubernetes.io/component: selenoid
{{- end }}
