// Anti-bot vendor adapter framework — types
//
// Defines the pluggable `VendorAdapter` contract used by
// `apps/api/src/lib/antibot/residential.ts` to delegate credential
// formatting + session-id injection to a specific anti-bot vendor
// (Bright Data, Smartproxy, etc.).
//
// The interface is intentionally narrow: an adapter knows how to take a
// target URL + an optional session-id and produce the proxy URL the
// existing undici `ProxyAgent` should dial. All transport-level concerns
// (TLS, retries, header injection) live in the higher-level provider.
//
// This is the **foundation** of T1.1 (post-ultracode item #16). The
// adapters below are stubs that produce correctly-formatted URLs from
// config. Production-grade tuning (sticky-session TTLs, geo targeting,
// bandwidth budgets) is a multi-week effort tracked separately.

export type VendorId = "brightdata" | "smartproxy" | "generic";

/**
 * Per-call options. The `sessionId` is generated by the residential
 * provider when rotation is enabled; the `target` is the absolute URL
 * being fetched. Vendors can use both to produce a session-pinned proxy
 * URL.
 */
export interface VendorBuildOptions {
  /** Absolute URL of the upstream target. Vendors use this for geo or domain hints. */
  target: string;
  /**
   * Optional session id; when omitted the adapter returns a URL that
   * will pin to a fresh exit on every request.
   */
  sessionId?: string;
  /**
   * Optional sticky-session TTL in milliseconds. Vendors that support
   * a vendor-side TTL (e.g. Smartproxy's `sesstime-<minutes>` token)
   * may embed it in the username to keep the same exit node for the
   * whole window. When omitted, vendors fall back to their own
   * default sticky window.
   */
  sessionTtlMs?: number;
  /**
   * Optional country / region hint (ISO-3166 alpha-2, e.g. "us",
   * "de"). Vendors that support geo targeting may embed it in the
   * username for routing.
   */
  geo?: string;
}

export interface VendorCredentials {
  /** Username (or empty for unauthenticated proxies). */
  username: string;
  /** Password (or empty for unauthenticated proxies). */
  password: string;
  /**
   * Hostname (no scheme). Example: "brd.superproxy.io".
   */
  host: string;
  /** Port number, e.g. 22225. */
  port: number;
}

/**
 * The vendor adapter contract. Implementations are pure functions of
 * (creds, options); they hold no state and are safe to construct at
 * config-load time.
 */
export interface VendorAdapter {
  /** Stable identifier, e.g. "brightdata". */
  readonly id: VendorId;
  /** Human-readable label for logs and metrics. */
  readonly label: string;
  /**
   * Validate that the supplied credentials are present and
   * well-formed. Throws a descriptive Error when the adapter cannot
   * be constructed.
   */
  validate(creds: VendorCredentials): void;
  /**
   * Build the proxy URL (with embedded credentials + session id) that
   * undici's `ProxyAgent` should dial.
   *
   * Example (Bright Data): `http://user-session-abc123@host:22225`
   */
  buildProxyUrl(creds: VendorCredentials, opts: VendorBuildOptions): string;
}

/**
 * Lightweight credentials object accepted by `createVendorAdapter`.
 * Host/port default to vendor-specific values when omitted.
 */
export interface VendorAdapterOptions {
  username?: string;
  password?: string;
  host?: string;
  port?: number;
  /** Pass-through to the adapter; vendor-specific. */
  zone?: string;
  /** Pass-through to the adapter; vendor-specific. */
  product?: string;
}
